#ifndef XRANDRBRIGHTNESS_GLOBAL_HPP
#define XRANDRBRIGHTNESS_GLOBAL_HPP

#include <QtCore/qglobal.h>

#if defined(XRANDRBRIGHTNESS_LIBRARY)
#  define XRANDRBRIGHTNESSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define XRANDRBRIGHTNESSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // XRANDRBRIGHTNESS_GLOBAL_HPP
