#ifndef RPIBLBRIGHTNESS_GLOBAL_HPP
#define RPIBLBRIGHTNESS_GLOBAL_HPP

#include <QtCore/qglobal.h>

#if defined(RPIBLBRIGHTNESS_LIBRARY)
#  define RPIBLBRIGHTNESSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define RPIBLBRIGHTNESSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // RPIBLBRIGHTNESS_GLOBAL_HPP
