#ifndef RPIGPIOBRIGHTNESS_GLOBAL_HPP
#define RPIGPIOBRIGHTNESS_GLOBAL_HPP

#include <QtCore/qglobal.h>

#if defined(RPIGPIOBRIGHTNESS_LIBRARY)
#  define RPIGPIOBRIGHTNESSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define RPIGPIOBRIGHTNESSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // RPIGPIOBRIGHTNESS_GLOBAL_HPP
